alias ls=ls
alias l="LC_COLLATE=C ls -lAhF"
alias mv="mv -iv"
alias cp="cp -iv"
alias sudo="sudo "
alias su="sudo -i"
alias rmd="sudo rm -r"
alias cpd="sudo cp -r"
alias p1="ping 1.1.1.1"
alias p8="ping 8.8.8.8"
alias vi="nvim"
alias v="nvim"
alias vv="nvim ."
alias ...="cd -"
# zsh
alias relo="source ~/.zshrc"
# git
alias g="git"
alias gs="git sync"
alias gsm="git sync main"
alias hold="git ca -m 'hold'"
# gh
alias ghg="gh browse"
# z
alias j=z
# yarn/npm/pnpm
alias p="pnpm"
alias pl="pnpm lint:fix"
alias prc="pnpm run checks"
alias pd="pnpm dev"
alias redep="pnpm clean && pnpm install"
alias gen="pnpm generate"
alias y="yarn"
alias ya="yarn add --ignore-optional"
alias yad="yarn add --ignore-optional --dev"
alias yr="yarn remove --ignore-optional"
alias ys="yarn start"
alias yb="yarn build"
alias yu="yarn upgrade --ignore-optional"
alias yf="yarn format"
alias yl="yarn lint"
alias yd="yarn dev"
alias story="yarn storybook:start"
# k8s
alias k="kubectl"
alias kgp="kubectl get-pods"
alias kpf="kubectl port-forwrd"
alias kx="kubectx"
# VS Code
alias c="code"
alias oc="code ."
