#!/usr/bin/zsh
# This hook is sourced after every virtualenv is activated.

# make the non-virtualenv prompt available
export OLD_PS1="$PS1"

# add virtualenv to prompt
function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`')'
}

local venv="$(virtualenv_info)"

PS1="
%{$fg[magenta]%}${venv} \\$PS1"

